## RSGB Public Radio Propagation Experiment
David Kirwan and John Ronan, EI7IG.

= Introduction
Earlier this year (2015) David was in the early stages of a M.Sc. project which required building an automated SDR receiver for the purposes of receiving signals from Jupiter [7]. John, EI7IG, though this was a perfect opportunity to test what components had been assembled so far to verify that everything was working as it should.

In February 2015, Steve Nichols, G0KYA put up an note on the RSGB forums and also on his own weblog with an announcement from the RSGB Propagation Studies Committee [2]. The public MW experiment to coincide with the March 20th partial solar eclipse. The UK and Ireland would witness more than 90% totality during the eclipse and this was an opportunity to perform simple experiments to demonstrate the Sun's effect on Earth's ionosphere, and how this ionisation affects the propagation of radio signals.

---
Insert: images/1.png here
Caption: Partial Solar Eclipse 20th March 2015 [6]
---

In short, MW radio stations which are located more than 500 km away are unlikely to be propagated during daylight hours due to their signals being absorbed by the D layer. However as we all have learned, the D layer does not exist during night time hours, as a result these radio signals are free to reflect from the higher E and F layers. This effect should also be possible to observe during a solar eclipse with a high totality percentage as would occur on the 20th March 2015.

G0KYA listed a number of radio stations which transmit signals in the MW range at various locations in the United Kingdom, Europe and also a number in Iceland [2][3]. The experiment called for choosing a station which is transmitting in the MW range and is also capable of being heard at the listeners location during the night time. This station should not be capable of being heard during the day time, the experiment called for a station which is further away than 500 km. The chosen radio station should then be tuned in to coincide with the beginning of the solar eclipse. The station receive power should be plotted against time. It was expected that the signal strength of the radio station should be strongest to coincide with the solar eclipse maximum, and similarly drop off once more as the eclipse reached its end.

It was immediately apparent to David that the antenna he had already constructed (15m dipole) would not be suitable for this experiment, and a suitable alternative was examined. Given the restrictions of the reception site, and time available, he elected to just run a long wire in the direction of the desired station. The existing HackRF [5] receiver was used despite being advertised as having an operating range between 10MHz and 6GHz. It was possible to receive signals down to about 500kHz in practice by ignoring the limits imposed by the firmware.

---
Insert: images/2.png here
Caption: Comparison of MW radio signal propagation during day and during solar eclipse
---

= Methodology
The following methodology was followed during this experiment:
* The antenna very simply consisted of a copper wire 80 m long attached to a long wire antenna terminator which had an SO239 connector.
* The listening site was longest in the East-West axis, and having the receiver positioned at the far west end of the site was most convenient. For this reason a radio station situated in an easterly direction was picked.
* The antenna was aimed in the general direction of the radio station chosen, and simply placed on the ground.
* The HackRF receiver was tuned to the chosen radio station [8]
* The AGC was deliberately switched off in order to get accurate power results.
* 2 MHz bandwidth of the spectrum was recorded during the entire length of the solar eclipse
* The signal strength of the radio station was then plotted against time for the period of time the solar eclipse was occuring.

---
Insert: images/3.png here
Caption: Location of listening site and radio station
---

The chosen radio station was Radio China International (1440 kHz) which was a powerful signal during the night time despite it being transmitted from Marnach in Luxembourg which is 950 km away from the listening site. The HackRF SDR receiver was tuned to 1440 kHz and IQ samples were recorded once the solar eclipse began. As the eclipse neared 20% totality the radio station slowly began to emerge from the background noise which was -70 dBm. The signal strength rose steadily until the eclipse maximum point which was at -28 dBm. It then fell in strength once more to average at -45db for the remainder of the eclise before finally returning to pre-eclipse levels. The station could no longer be heard once the signal strength went below -55dB. The results were submitted to the RSGB Propagation Studies Committee [1] for inclusion in the overall experiment.

---
Insert: images/4.png here
Caption: Station signal strength during the eclipse
---

At the time of the experiment, the specifications of the HackRF were not guaranteed below 10Mhz this has since been revised down to 1MHz.  In practice, it does work as low as 500kHz, with care.


[1] http://forums.thersgb.org/index.php?threads/partial-solar-eclipse-propagation-experiment-march-20th-2015.125
[2] http://www.g0kya.blogspot.ie/2015/02/partial-solar-eclipse-propagation.html
[3] http://www.rsgb.org/eclipse-2015
[4] http://www.nrcdxas.org/articles/BevAnt0876.pdf
[5] http://greatscottgadgets.com/hackrf/
[6] http://www.timeanddate.com/eclipse/in/ireland/kilkenny
[7] http://radiojove.gsfc.nasa.gov
[8] http://english.cri.cn/
